exp_name: 'generation '
norm_loudness_flag: True
unvoiced_flag: True
trained_dirpath: ''
input_dirpath: 'testset'
crepe_path: 'data_utils/crepe_models/full.pth'
octaves: [-2, -1, 0, 1, 2]

hydra:
  run:
    dir: outputs/null